name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc && \
          echo "@anima:registry=https://npm.animaapp.com/" >> ~/.npmrc && \
          echo "//npm.animaapp.com/:_authToken=\${NPM_TOKEN}" >> ~/.npmrc && \
          npm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run release
